/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ysu_itrace_trackers_TobiiTracker_BackgroundThread */

#ifndef _Included_edu_ysu_itrace_trackers_TobiiTracker_BackgroundThread
#define _Included_edu_ysu_itrace_trackers_TobiiTracker_BackgroundThread
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_ysu_itrace_trackers_TobiiTracker_BackgroundThread_MIN_PRIORITY
#define edu_ysu_itrace_trackers_TobiiTracker_BackgroundThread_MIN_PRIORITY 1L
#undef edu_ysu_itrace_trackers_TobiiTracker_BackgroundThread_NORM_PRIORITY
#define edu_ysu_itrace_trackers_TobiiTracker_BackgroundThread_NORM_PRIORITY 5L
#undef edu_ysu_itrace_trackers_TobiiTracker_BackgroundThread_MAX_PRIORITY
#define edu_ysu_itrace_trackers_TobiiTracker_BackgroundThread_MAX_PRIORITY 10L
/*
 * Class:     edu_ysu_itrace_trackers_TobiiTracker_BackgroundThread
 * Method:    jniBeginTobiiMainloop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ysu_itrace_trackers_TobiiTracker_00024BackgroundThread_jniBeginTobiiMainloop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
