/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ysu_itrace_trackers_EyeXTracker */

#ifndef _Included_edu_ysu_itrace_trackers_EyeXTracker
#define _Included_edu_ysu_itrace_trackers_EyeXTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_ysu_itrace_trackers_EyeXTracker
 * Method:    disconnectEyeTracker
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_ysu_itrace_trackers_EyeXTracker_disconnectEyeTracker
  (JNIEnv *, jobject);

/*
 * Class:     edu_ysu_itrace_trackers_EyeXTracker
 * Method:    connectEyeTracker
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ysu_itrace_trackers_EyeXTracker_connectEyeTracker
  (JNIEnv *, jobject);

/*
* Class:     edu_ysu_itrace_trackers_EyeXTracker
* Method:    register
* Signature: ()Z
*/
JNIEXPORT jboolean JNICALL Java_edu_ysu_itrace_trackers_EyeXTracker_register
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
