/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ysu_itrace_jni_EyeTracker */

#ifndef _Included_edu_ysu_itrace_jni_EyeTracker
#define _Included_edu_ysu_itrace_jni_EyeTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_ysu_itrace_jni_EyeTracker
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_ysu_itrace_jni_EyeTracker_initialize
  (JNIEnv *, jobject);

/*
 * Class:     edu_ysu_itrace_jni_EyeTracker
 * Method:    uninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_ysu_itrace_jni_EyeTracker_uninitialize
  (JNIEnv *, jobject);

/*
 * Class:     edu_ysu_itrace_jni_EyeTracker
 * Method:    getFixation
 * Signature: ()Ljava/awt/geom/Point2D;
 */
JNIEXPORT jobject JNICALL Java_edu_ysu_itrace_jni_EyeTracker_getFixation
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
