/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ysu_itrace_trackers_EyeXTracker */

#ifndef _Included_edu_ysu_itrace_trackers_EyeXTracker
#define _Included_edu_ysu_itrace_trackers_EyeXTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_ysu_itrace_trackers_EyeXTracker
 * Method:    jniConnectEyeXTracker
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ysu_itrace_trackers_EyeXTracker_jniConnectEyeXTracker
  (JNIEnv *, jobject);

/*
 * Class:     edu_ysu_itrace_trackers_EyeXTracker
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_ysu_itrace_trackers_EyeXTracker_close
  (JNIEnv *, jobject);

/*
 * Class:     edu_ysu_itrace_trackers_EyeXTracker
 * Method:    startTracking
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_ysu_itrace_trackers_EyeXTracker_startTracking
  (JNIEnv *, jobject);

/*
 * Class:     edu_ysu_itrace_trackers_EyeXTracker
 * Method:    stopTracking
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_ysu_itrace_trackers_EyeXTracker_stopTracking
  (JNIEnv *, jobject);

/*
 * Class:     edu_ysu_itrace_trackers_EyeXTracker
 * Method:    registerAssemblyHandler
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_ysu_itrace_trackers_EyeXTracker_registerAssemblyHandler
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
